### ISSUE TITLE
Input file in configuration files

### ISSUE THREAD

**Issue by pandatix** [ctfer-io/ctfd-setup#82]
When creating a configuration file that consumes external files, those are not consumed as expected.
For instance, I would like to write the following.

```yaml
# ...

theme:
  logo:
    from_file: logo.png
  footer: |
    <div align="center">
      <h2>My Footer</h2>
    </div>
```

This fails: `logo.png` is not imported...
I'll work on a PR to fix this one, in parallel on the JSON schema validation I'm working on :smiley:
